version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: "kimai-mysql-test-cont"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "kimai2_test"
      MYSQL_USER: "kimai2_test"
      MYSQL_PASSWORD: "kimai2_test"
      MYSQL_DATABASE: "kimai2_test"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-config/mysql:/etc/mysql/conf.d
    networks:
      - default
  
  pgsql:
    image: postgres:14.2-alpine3.15
    container_name: "kimai-pgsql-test-cont"
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: "kimai2_test"
      POSTGRES_PASSWORD: "kimai2_test"
      POSTGRES_DB: "kimai2_test"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./docker-config/postgresql/postgresql.conf:/var/lib/postgresql/postgresql.conf
    networks:
      - default

  composer:
    build:
      context: "./docker-config/composer"
    image: composer_kimai-test:0.0.1
    volumes:
      - ./kimai2:/app
    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  pgsql-data:
    driver: local
