version: '3'

services:

  php-console:
    build:
      context: ./docker-config/php
    image: "kimai_php_console"
    volumes:
      - ./kimai:/app
    networks:
      - default

  mysql:
    image: mysql:5.7
    container_name: "kimai-mysql-test-cont"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "kimai_test"
      MYSQL_USER: "kimai_test"
      MYSQL_PASSWORD: "kimai_test"
      MYSQL_DATABASE: "kimai_test"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-config/mysql:/etc/mysql/conf.d
    networks:
      - default
  
  pgsql:
    image: postgres:14.2-alpine3.15
    container_name: "kimai-pgsql-test-cont"
    restart: unless-stopped
    tty: true
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: "kimai_test"
      POSTGRES_PASSWORD: "kimai_test"
      POSTGRES_DB: "kimai_test"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./docker-config/postgresql/postgresql.conf:/var/lib/postgresql/postgresql.conf
    networks:
      - default

  composer:
    build:
      context: "./docker-config/composer"
    image: composer_kimai-test:0.0.1
    volumes:
      - ./kimai:/app
    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  pgsql-data:
    driver: local
